# Generated by Django 5.1.6 on 2025-08-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsexshop', '0004_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritocompras',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='domiciliario',
            name='Contrasena',
        ),
        migrations.AlterField(
            model_name='carritocompras',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='carritocompras',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='Precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
