# Generated by Django 5.1.6 on 2025-08-08 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsexshop', '0005_remove_carritocompras_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('NombreUsuario', models.CharField(max_length=45)),
                ('CelularUsuario', models.CharField(max_length=45)),
                ('FechaCompra', models.DateField()),
                ('FechaEntrega', models.DateField()),
                ('Direccion', models.CharField(max_length=45)),
                ('CodigoPedido', models.IntegerField()),
                ('IdDomiciliario', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Registro de Pedido',
                'verbose_name_plural': 'Registros de Pedidos',
                'db_table': 'registropedido',
            },
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsexshop.usuario'),
        ),
    ]
