# Generated by Django 5.1.6 on 2025-08-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsexshop', '0006_registropedido_carritocompras_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registropedido',
            options={'managed': False, 'verbose_name': 'Registro de Pedido', 'verbose_name_plural': 'Registros de Pedidos'},
        ),
    ]
