# Generated by Django 5.1.6 on 2025-08-08 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsexshop', '0007_alter_registropedido_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroPedido',
        ),
        migrations.AlterField(
            model_name='carritocompras',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appsexshop.usuario'),
        ),
    ]
