# Generated by Django 5.1.6 on 2025-08-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsexshop', '0008_delete_registropedido_alter_carritocompras_usuario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carritocompras',
            table='appsexshop_carritocompras',
        ),
    ]
